export const GET_AUTO_PILOT_COUNTRYS = 'GET_AUTO_PILOT_COUNTRYS';
export const GET_AUTO_PILOT_COUNTRYS_SUCCESS = 'GET_AUTO_PILOT_COUNTRYS_SUCCESS';
export const GET_AUTO_PILOT_COUNTRYS_FAIL = 'GET_AUTO_PILOT_COUNTRYS_FAIL';