export const GET_AUTO_PILOT_COUNTRYS = 'GET_AUTO_PILOT_COUNTRYS';
export const GET_AUTO_PILOT_COUNTRYS_SUCCESS = 'GET_AUTO_PILOT_COUNTRYS_SUCCESS';
export const GET_AUTO_PILOT_COUNTRYS_FAIL = 'GET_AUTO_PILOT_COUNTRYS_FAIL';

export const GET_COVER_GENIUS_ORDERS = 'GET_COVER_GENIUS_ORDERS';
export const GET_COVER_GENIUS_ORDERS_SUCCESS = 'GET_COVER_GENIUS_ORDERS_SUCCESS';
export const GET_COVER_GENIUS_ORDERS_FAIL = 'GET_COVER_GENIUS_ORDERS_FAIL';